services:
  - type: web
    name: aircombat-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false # Set this in the Render Dashboard (MongoDB Atlas string)
      - key: PORT
        value: 10000
